# This is a extended json package definition file 
# We allow simple comments (lines starting with a hash symbol)
{
    "ubuntu-oneiric": {
        "django-nose-selenium": {
            "version": "0.7.3"
        },
        "pycrypto": {
            "version": "2.3"
        },
        "python-cloudfiles": {
            "version": "1.7.9.3"
        }
    },
    "rhel-6": {
        #the base is 2.0, need to upgrade
        "pycrypto": {
            "version": "2.5",
            "options": "--upgrade"
        },
        #the newest we can get is 1.3.3 from epel/rhel
        #this causes issues like the following
        #https://answers.launchpad.net/nova/+question/174160
        #https://answers.launchpad.net/nova/+question/185116
        "PasteDeploy": {
            "version": "1.5"
        },
        "PasteScript": {
            "version": "1.7.5"
        },
        "Paste": {
            "version": "1.7.5.1"
        },
        "SQLAlchemy": {
            "version": "0.7.5"
        },
        "sqlalchemy-migrate": {
            "version": "0.7.2"
        },
        "python-cloudfiles": {
            "version": "1.7.9.3"
        },
        "CherryPy": {
            "version": "3.2.2"
        },
        #the base os doesn't have static files which
        #seems only in 1.3 or greater
        "django" : {
            "version": "1.3.1"
        },
        "django-nose" : {
            "version": "0.1.3"
        },
        "django-nose-selenium": {
            "version": "0.7.3"
        },
        "django-registration" : {
            "version": "0.7"
        },
        "django-mailer" : {
            "version": "0.1.0"
        },
        "django-staticfiles" : {
            "version": "1.1.2"
        },
        "Routes": {
            "version": "1.12.3"
        }
    },
    "fedora-16": {
        # rpm 1.7.9.1 does not have exceptions.Error
        "python-cloudfiles": {
            "version": "1.7.9.3"
        },
        "django-nose" : {
            "version": "0.1.3"
        }
    }
}
